import { createBrowserRouter, Navigate } from 'react-router-dom'
import { AppLayout } from '@/components/layout'
import {
  DashboardPage,
  EmployeeListPage,
  EmployeeDetailPage,
  AddEmployeePage,
  ClientListPage,
  ClientDetailPage,
  AddClientPage,
  SiteListPage,
  SiteDetailPage,
  AddSitePage,
  AssignGuardPage,
  OperationsPage,
  AttendancePage,
  RecordAttendancePage,
  ContractsPage,
  NewContractPage,
  RenewContractPage,
  ViewContractPage,
  PayrollPage,
  ProcessPayrollPage,
  ExpensesPage,
  ReportsPage,
  SettingsPage,
} from '@/pages'

export const router = createBrowserRouter([
  {
    path: '/',
    element: <AppLayout />,
    children: [
      { index: true, element: <Navigate to="/dashboard" replace /> },
      { path: 'dashboard', element: <DashboardPage /> },
      { path: 'employees', element: <EmployeeListPage /> },
      { path: 'employees/new', element: <AddEmployeePage /> },
      { path: 'employees/:id', element: <EmployeeDetailPage /> },
      { path: 'employees/:id/edit', element: <AddEmployeePage /> },
      { path: 'clients', element: <ClientListPage /> },
      { path: 'clients/new', element: <AddClientPage /> },
      { path: 'clients/:id', element: <ClientDetailPage /> },
      { path: 'clients/:id/edit', element: <AddClientPage /> },
      { path: 'sites', element: <SiteListPage /> },
      { path: 'sites/new', element: <AddSitePage /> },
      { path: 'sites/:id', element: <SiteDetailPage /> },
      { path: 'sites/:id/edit', element: <AddSitePage /> },
      { path: 'sites/:id/assign-guard', element: <AssignGuardPage /> },
      { path: 'operations', element: <OperationsPage /> },
      { path: 'operations/assign-guard', element: <AssignGuardPage /> },
      { path: 'attendance', element: <AttendancePage /> },
      { path: 'attendance/record', element: <RecordAttendancePage /> },
      { path: 'contracts', element: <ContractsPage /> },
      { path: 'contracts/new', element: <NewContractPage /> },
      { path: 'contracts/:id', element: <ViewContractPage /> },
      { path: 'contracts/:id/renew', element: <RenewContractPage /> },
      { path: 'payroll', element: <PayrollPage /> },
      { path: 'payroll/process', element: <ProcessPayrollPage /> },
      { path: 'expenses', element: <ExpensesPage /> },
      { path: 'reports', element: <ReportsPage /> },
      { path: 'settings', element: <SettingsPage /> },
    ],
  },
])
